spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  mvc:
    format:
      time: iso
      date: iso

  datasource:
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/socialmedia
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        format_sql: true
        show_sql: true
    open-in-view: false
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 594878245202-6ijpktq7mvlcuopjb412judvts2bb2ml.apps.googleusercontent.com
            clientSecret: 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
            redirectUri: http://localhost:8080/login/oauth2/code/google

db:
  limit:
    posts: 3
    users : 5

